sudo: required
services:
  - docker

before_install: 
  - docker build -t <NAME_OF_YOUR_IMAGE> -f Dockerfile.dev .

script: 
  - docker run -e CI=true <NAME_OF_YOUR_IMAGE> npm run test

deploy:
  provider: elasticbeanstalk
  region: "<AWS_REGION_OF_YOUR_APP>"
  app: "<APP_NAME>"
  env: "<APP_ENV_NAME>"
  bucket_name: "<BUCKET_NAME"
  bucket_path: "<APP_NAME>"
  on:
    branch: main
  access_key_id: "$<YOUR_AWS_ACCESS_KEY>"
  secret_access_key: "$<YOUR_AWS_SECRET_KEY>"
